specVersion: 0.2.0
name: stafi-dao-query
version: 1.0.0
description: 'stafi-dao-query'
repository: 'https://github.com/makefriendwithtime/stafi-dao-query'
schema:
  file: ./schema.graphql
network:
  endpoint: wss://moonbeam-alpha.api.onfinality.io/public-ws
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  dictionary: 'https://api.subquery.network/sq/subquery/moonbase-alpha-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/FrontierEvm
    startBlock: 752073
    processor:
      file: './node_modules/@subql/contract-processors/dist/frontierEvm.js'
      options:
        abi: governance
        address: '0xaB1421B7298cC690bF7Dc289aE29B96CAba48A00'
      assets:
        governance:
          file: './abi.governance.json'
      mapping:
        file: './dist/index.js'
        handlers:
          - handler: handleFrontierEvmEvent
            kind: substrate/FrontierEvmEvent
            filter:
              topics:
                - StartGovern(address indexed creator,uint number,uint governType,uint256 startDate,uint256 endDate,uint uintValue,string strValue,uint256 totalVoter)
#                - VoteByNumber(address indexed votor,uint number,uint governType,uint256 totalVoter,uint approveVoter,uint opposeVoter,bool success)